#!/usr/bin/env bash
# script to about subdomian

name=$2
if [ "$#" -lt 2 ];
then
    dig +nocmd "www.$1" a +noall +answer | awk '{print "The subdomain www is a", $4, "record and points to", $5}'
    dig +nocmd "lb-01.$1" a +noall +answer | awk '{print "The subdomain lb-01 is a", $4, "record and points to", $5}'
    dig +nocmd "web-01.$1" a +noall +answer | awk '{print "The subdomain web-01 is a", $4, "record and points to", $5}'
    dig +nocmd "web-02.$1" a +noall +answer | awk '{print "The subdomain web-02 is a", $4, "record and points to", $5}'
else
    name=$(dig +nocmd "$2.$1" a +noall +answer | cut -d '.' -f1)
    record=$(dig +nocmd "$2.$1" a +noall +answer | awk '{print $4}')
    add=$(dig +nocmd "$2.$1" a +noall +answer | awk '{print $5}')
    echo "The subdomain $name is a $record record and points to $add"
fi
