#!/usr/bin/env bash
# manages manage_my_process
if [[ $# -eq 1 ]]; then
	if [[ "$1" = "start" ]];
	then
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
	elif [[ "$1" = "stop" ]];
	then
		if test -f "/var/run/my_process.pid";then
			kill -s SIGKILL "$(cat /var/run/my_process.pid)"
			rm /var/run/my_process.pid
		fi
		echo "manage_my_process stopped"
	elif [[ "$1" = "restart" ]];
	then
		if test -f "/var/run/my_process.pid";then
			kill -s SIGKILL "$(cat /var/run/my_process.pid)"
			rm /var/run/my_process.pid
		fi
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process restarted"
	else
		echo "Usage: manage_my_process {start|stop|restart}"
	fi
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi